import { Transaction, BudgetCategory } from './schema';

export const INITIAL_BUDGETS: BudgetCategory[] = [
  {
    category: 'Housing & Utilities',
    monthly_limit: 1500,
    icon: 'home',
    subtitle: 'Rent, water, electricity, gas',
  },
  {
    category: 'Food & Dining',
    monthly_limit: 700,
    icon: 'restaurant',
    subtitle: 'Groceries, cafes, dining out',
  },
  {
    category: 'Shopping & Tech',
    monthly_limit: 400,
    icon: 'shopping-bag',
    subtitle: 'Hardware, apparel, software',
  },
  {
    category: 'Entertainment',
    monthly_limit: 250,
    icon: 'film',
    subtitle: 'Streaming, cinema, concerts',
  },
  {
    category: 'Transport',
    monthly_limit: 200,
    icon: 'navigation',
    subtitle: 'Fuel, transit pass, rideshare',
  },
  {
    category: 'Health & Wellness',
    monthly_limit: 300,
    icon: 'activity',
    subtitle: 'Gym, medical, pharmacy',
  },
];

export const DEMO_TRANSACTIONS: Omit<Transaction, 'id' | 'created_at'>[] = [
  {
    amount: 129.00,
    type: 'expense',
    category: 'Shopping & Tech',
    merchant: 'Apple Store',
    note: 'Tech Hardware',
    tags: '#work #tech',
    date: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // Today 2 hours ago
    payment_method: 'Direct Debit',
    is_split: 0,
    split_count: 1,
  },
  {
    amount: 6.50,
    type: 'expense',
    category: 'Food & Dining',
    merchant: 'Blue Bottle Coffee',
    note: 'Espresso & Pastry',
    tags: '#coffee #morning',
    date: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(), // Today morning
    payment_method: 'Zenith Card',
    is_split: 0,
    split_count: 1,
  },
  {
    amount: 84.20,
    type: 'expense',
    category: 'Food & Dining',
    merchant: 'Whole Foods Market',
    note: 'Weekly organic pantry run',
    tags: '#groceries #organic',
    date: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    payment_method: 'Apple Pay',
    is_split: 0,
    split_count: 1,
  },
  {
    amount: 16.99,
    type: 'expense',
    category: 'Entertainment',
    merchant: 'Spotify Family',
    note: 'Monthly streaming subscription',
    tags: '#recurring #music',
    date: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
    payment_method: 'Zenith Card',
    is_split: 0,
    split_count: 1,
  },
  {
    amount: 15.00,
    type: 'expense',
    category: 'Shopping & Tech',
    merchant: 'Figma Pro',
    note: 'Design tool license',
    tags: '#work-expense #design',
    date: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    payment_method: 'Credit Card',
    is_split: 0,
    split_count: 1,
  },
  {
    amount: 24.80,
    type: 'expense',
    category: 'Transport',
    merchant: 'Uber Ride',
    note: 'Airport transit ride',
    tags: '#transit',
    date: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(), // Yesterday
    payment_method: 'Apple Pay',
    is_split: 0,
    split_count: 1,
  },
  {
    amount: 18.45,
    type: 'expense',
    category: 'Food & Dining',
    merchant: 'Sweetgreen',
    note: 'Salad lunch with Elena',
    tags: '#lunch #split',
    date: new Date(Date.now() - 28 * 60 * 60 * 1000).toISOString(),
    payment_method: 'Zenith Card',
    is_split: 1,
    split_count: 2,
  },
  {
    amount: 220.00,
    type: 'expense',
    category: 'Health & Wellness',
    merchant: 'Equinox Fitness',
    note: 'Monthly club membership',
    tags: '#health #gym',
    date: new Date(Date.now() - 32 * 60 * 60 * 1000).toISOString(),
    payment_method: 'Direct Debit',
    is_split: 0,
    split_count: 1,
  },
  {
    amount: 1400.00,
    type: 'expense',
    category: 'Housing & Utilities',
    merchant: 'Apex Living Apartments',
    note: 'Monthly rent & water utility',
    tags: '#rent #housing',
    date: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
    payment_method: 'Bank Transfer',
    is_split: 0,
    split_count: 1,
  },
  {
    amount: 2450.00,
    type: 'income',
    category: 'Income',
    merchant: 'Client Invoice #1042',
    note: 'Full-stack UI/UX sprint payout',
    tags: '#freelance #invoice',
    date: new Date(Date.now() - 40 * 60 * 60 * 1000).toISOString(),
    payment_method: 'Direct Deposit',
    is_split: 0,
    split_count: 1,
  },
  {
    amount: 3970.00,
    type: 'income',
    category: 'Income',
    merchant: 'Primary Salary Payout',
    note: 'Monthly consulting retainer',
    tags: '#salary',
    date: new Date(Date.now() - 200 * 60 * 60 * 1000).toISOString(),
    payment_method: 'Wire Transfer',
    is_split: 0,
    split_count: 1,
  },
];
